config/routes.rb
Chito::Application.routes.draw do
  constraints(IndexMatch) do
    match '/' => 'index#index'
    match '/index.rss' => 'index#index', :as => :index_feed, :format => 'rss'
    match '/index_plugin.css' => 'index#plugin_css', :as => :index_plugin_css
  end
  root :to => 'posts#index'
  match '/plugin.css' => 'blog#plugin_css', :as => :plugin_css
  match '/simple_captcha(/:action)' => 'simple_captcha', :as => :simple_captcha
  match '/simple_captcha_ajax' => 'simple_captcha#simple_captcha_ajax'
  match '/:year/:month/:day/:permalink.:id.:format' => 'posts#show', :constraints => { :year => /(19|20)\d\d/, :month => /[0|1]?\d/, :day => /[0-3]?\d/ }, :as => :post_permalink
  match ':year/:month/:day' => 'posts#index', :as => :day, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ }, :as => :posts_on
  match ':year/:month' => 'posts#index', :as => :archive, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ }

  resources :posts do
    member do
        get :cancel_comment_notifier
    end 
  end

  resources :categories do
    resources :posts
  end
  resources :posts do
    resources :comments 
  end

  resources :pages
  resources :messages
  match '/comments.:format' => 'comments#index', :as => :comments
  match '/comments/:id/mark_as_spam.:format' => 'comments#mark_as_spam', :as => :mark_comment_as_spam
  match '/tag/*tag_name' => 'posts#index', :as => :tag_posts
  match '/category/*category_permalink' => 'posts#index', :as => :category_permalink_posts
  match '/admin/links/set_link_title' => 'admin/links#set_link_title'
  match '/admin/links/set_link_url' => 'admin/links#set_link_url'
  match '/admin/links/set_link_info' => 'admin/links#set_link_info'
  match '/admin/categories/set_category_name' => 'admin/categories#set_category_name'
  match '/admin/categories/set_category_info' => 'admin/categories#set_category_info'
  match '/admin/categories/set_category_permalink' => 'admin/categories#set_category_permalink'
  match '/admin/users/set_user_bind_domain' => 'admin/users#set_user_bind_domain'
  match '/admin/groups/set_group_space' => 'admin/groups#set_group_space'
  match '/admin/groups/set_group_file_size_limit' => 'admin/groups#set_group_file_size_limit'
  match '/admin/indices/set_index_title' => 'admin/indices#set_index_title'
  match '/admin/indices/set_index_bind_domain' => 'admin/indices#set_index_bind_domain'
  match '/admin/indices/set_index_info' => 'admin/indices#set_index_info'

  namespace :admin do
    resources :posts do
        collection do
            post :destroy_selected
            post :recategory_selected
        end
        member do
            post :autosave
        end
    end

    resources :drafts do
        collection do
            post :destroy_selected
        end
        member do
            post :autosave
        end
    end

    resources :trash do
        collection do
            post :destroy_all
        end
        member do
            post :restore
        end
    end

    resources :pages do
        member do
            post :enable_fontpage
            post :cancel_fontpage
        end
        member do
            post :autosave
        end
    end
      
    resources :users do 
        member do
            post :set_group
        end
    end
    
    resources :groups do
        member do
            post :set_group_space
            post :set_group_name
            post :set_group_file_size_limit
            post :set_api_status
            post :set_no_index_status
        end
    end

    resources :indices do
        member do
            post :add_manager
            post :remove_manager
            get :settings
            post :change_settings
            post :sidebar_position
            post :save_avatar
        end
    end

    resources :comments do
        collection do
            delete :destroy_selected
        end
    end

    resources :messages do
        collection do
            delete :destroy_selected
        end
    end

    resources :trackbacks do
        collection do
            delete :destroy_selected
        end
    end

    resources :talks

    resources :spams do
        collection do
            delete :destroy_selected
        end
        member do
            post :pass
        end
    end

    resources :categories do
        resources :posts
        resources :drafts
        collection do
            post :set_position
        end
    end
      
    resources :links do
        collection do
            post :set_position
        end
    end

    resources :files do
        collection do
            get :list
            get :create_file_iframe
            post :create_file_iframe
            delete :delete_file
            delete :delete_dir
            post :create_file
            post :create_dir
        end
    end
      
    resources :feedbacks do
        collection do
            delete :destroy_selected
        end
    end
    
    resources :articles do
        collection do
            delete :destroy_selected
        end
        member do
            post :increase_rank
            post :decrease_rank
        end
    end

  end

  #match '/latex_formula/make_png' => 'latex_formula#make_png'

  match '/xmlrpc' => 'xmlrpc/meta_weblog#index', :format => 'xml'
  match '/xml_rpc' => 'xmlrpc/meta_weblog#index', :format => 'xml'

  match '/add' => 'blog#add'
  match '/login' => 'blog#login', :as => :login
  match '/forgot_password' => 'blog#forgot_password', :as => :forgot_password
  match '/reset_password/:key' => 'blog#reset_password', :as => :reset_password
  match '/guestbook' => 'blog#guestbook', :as => :guestbook
  match '/articles/:id/:seo_title.:format' => 'posts#show'
  match '/rss' => 'posts#index', :format => 'rss'
  match '/feed' => 'posts#index', :as => :feed, :format => 'rss'
  match '/show/:id.:format' => 'posts#show'
  match '/site.:format' => 'blog#index', :as => :site
  match '/setup' => 'site#setup'
  match '/pages/:id/:seo_title.:format' => 'pages#show'
  match '/themes/user/:theme/*anything' => 'theme#user_theme_file'
  match '/themes/index/:theme/*anything' => 'theme#index_theme_file'
  match '/plugins/:plugin/*anything' => 'plugin#file'
  match '/admin' => 'admin/dashboard#index', :as => :admin
  match '/admin/logout' => 'admin/dashboard#logout'
  match '/admin/dashboardbar_position' => 'admin/dashboard#dashboardbar_position'
  match '/admin/plugins/(:plugin_id)' => 'admin/plugins#index'
  match '/admin/plugin_config/:plugin_id' => 'admin/plugins#plugin'
  match '/admin/remote_form/:plugin/:view' => 'admin/plugins#remote_form'
  match '/admin/remote_update' => 'admin/plugins#remote_update'
  match '/admin/themes/:action/(:id)' => 'admin/themes#index'
  match '/admin/themesettings/:action/(:id)' => 'admin/themesettings#index'
  match '/admin/sidebar/:action/(:id)' => 'admin/sidebar#index'
  match '/admin/navbar/:action/(:id)' => 'admin/navbar#index'
  match '/admin/postbar/:action/(:id)' => 'admin/postbar#index'
  match '/admin/settings/comment/setting_area' => 'admin/settings#comment_setting_area', :as => :admin_comment_setting_area
  match '/admin/settings/comment/set_comment_system' => 'admin/settings#set_comment_system_settings', :as => :admin_set_comment_system
  match '/admin/settings/:action/(:id)' => 'admin/settings#index'
  match '/admin/rss/:action/(:id)' => 'admin/rss#index'
  match '/admin/site/:action/(:id)' => 'admin/site#index'
  match '/admin/blog/:action/(:id)' => 'admin/blog#index'
  match '/admin/systeminfo/:action/(:id)' => 'admin/systeminfo#index'
  match '/admin/:action/:id' => 'admin/dashboard#index'
  match '/*permalink' => 'pages#show', :as => :page_permalink
end

app/controllers/admin/indices_controller.rb
class Admin::IndicesController < Admin::BaseController
    self.prepend_view_path(IndexTheme::PATH) 
    before_filter :chito_admin_authorize, :only => [:index, :create, :add_manager, :remove_manager, :destroy]
    before_filter :index_manager_authorize, :only => [:show, :settings, :change_settings, :sidebar_position, :save_avatar]
    in_place_edit_for :index, :title
    in_place_edit_for :index, :info
    in_place_edit_for :index, :bind_domain


  def show
    @posts = @index.posts.paginate :per_page => 30, :page => params[:page]
  end

  def settings
    @index_theme_list = IndexTheme::LIST
    @overlap = {}
    get_index_sidebars
  end

  def save_avatar
    file = params[:file] && params[:file][:data]
    if file.respond_to?('content_type')  && file.content_type =~ /^image/ && file.length < 204800
        @index.avatar = file
        notice_stickie t(:avatar_uploaded, :scope => [:txt, :controller, :admin, :indices])
    else
        error_stickie t(:avatar_format_error, :scope => [:txt, :controller, :admin, :indices])
    end
    redirect_to :action => "settings"
  end

  def change_settings
    return unless request.post?
    notice_stickie(t(:config_updated, :scope => [:txt, :controller, :admin, :base])) if @index.update_attributes(params[:index])
    redirect_to :action => "settings"
  end

  def sidebar_position
    get_index_sidebars
    for field in params[:fields]
      next unless params[field.to_sym]
      params[field.to_sym].each_with_index do |id,idx| 
        bar = @all_bars.detect{|s| s.id==id.to_sym}
        bar.position = idx
        bar.field = field
        bar.show = (field.to_sym != :disable)
      end
    end
    notice_stickie(t(:sidebars_updated, :scope => [:txt, :controller, :admin, :sidebar])) if @index.update_attributes(params[:index])
    redirect_to :action => "settings"
  end

  def index
    @indices = Index.order('id')
  end

  def create
    @index = Index.new(params[:index])
    if @index.save
        @created = true
    else
        error_stickie(@index.errors.full_messages * "; ")
    end
  end

  def add_manager
    @index = Index.find(params[:id])
    user = User.find_by_name(params[:user_name])
    if user && @index.users << user
        @added = true
    else
        error_stickie t(:no_such_user, :scope => [:txt, :controller, :admin, :indices])
    end
  end

  def remove_manager
    @index = Index.find(params[:id])
    user = User.find(params[:user_id])
    if user && @index.users.delete(user)
        @deleted = true
    else
        error_stickie t(:no_such_user, :scope => [:txt, :controller, :admin, :indices])
    end
  end

  def destroy
    index = Index.find(params[:id])
    notice_stickie t(:index_deleted, :scope => [:txt, :controller, :admin, :indices]) if index.destroy 
    redirect_to admin_indices_path
  end

end

app/helpers/indices_helper.rb
module IndicesHelper

end

app/views/admin/indices/_bars_config.html.erb
<% @fields = ['chito_default'] -%>
<% @overlap[:chito_default] = :vertical -%>
<% @disable_bars = @all_bars.reject{|b| b.show?}.sort_by{|x| x.position} -%>
<ul id='chito_default' class="vbars">
    <div class="bars_title"><%= t(:sidebar, :scope => [:txt, :view, :admin, :sidebar]) %></div>
    <% for bar in @enable_bars -%>
	<%= show_bar(bar, :index) %>
    <% end -%>
</ul>

app/views/admin/indices/_index.html.erb
    <tr id="index_<%= @index.id %>" class="<%= cycle("odd", "") %>">
	    <td class="index_title_col">
			<%= in_place_edit :index, :title, @index.id, @index.title.to_s %>
	    </td>
	    <td class="index_bind_domain_col"><%= in_place_edit :index, :bind_domain, @index.id, @index.bind_domain.to_s %></td>
            <td class="index_info_col"><%= in_place_edit :index, :info, @index.id, @index.info.to_s %></td>
	    <td class="index_theme_col"><%= @index.theme %></td>
	    <td class="index_managers_col">
                <%= form_tag( add_manager_admin_index_path(@index),
                             :remote => true, :id => "rform_#{@index.id}", :onsubmit => "return false;"
			    ) do %>
		    <%= text_field_tag 'user_name', "", :size => 8  %>
	            <%= submit_tag t(:add, :scope => [:txt, :view, :admin, :indices]), :id => "ss_#{@index.id}", :autocomplete => 'off', :id => "subm_#{@index.id}" %> 
	        <% end %>	
                <script type="text/javascript">
                //<![CDATA[
                $('#subm_<%= @index.id %>').click(function(){
                        $.post('<%= add_manager_admin_index_path(@index) %>',$('#rform_<%= @index.id %>').find('input').serialize());
                        return false;
                 });
                //]]>
                </script>
                <div id="index_users_<%= @index.id %>">
                    <%= render :partial => "managers" %>
                </div>
            </td>

	    <td class="action_col delete"><%= link_to t(:delete, :scope => [:txt, :view, :admin, :indices]), admin_index_path(@index), :class => "delete", 
		:confirm => t(:delete_index?, :scope => [:txt, :view, :admin, :indices], :index => @index.title), :method => :delete %></td>
    </tr>

app/views/admin/indices/_managers.html.erb
<% for user in @index.users -%>
    <div class="manager" style="padding-top:5px;">
        <%= form_tag( remove_manager_admin_index_path(@index, :user_id => user.id),
                     :remote => true, :id => "rform_2_#{@index.id}", :onsubmit => "return false;"
			    ) do %>
            <span><%= user.name %></span>
	    <%= submit_tag t(:remove, :scope => [:txt, :view, :admin, :indices]), :id => "sr_#{@index.id}", :autocomplete => 'off', :id => "subm_2_#{@index.id}" %> 
        <% end -%>
    </div>
    <script type="text/javascript">
    //<![CDATA[
    $('#subm_2_<%= @index.id %>').click(function(){
            $.post('<%= remove_manager_admin_index_path(@index, :user_id => user.id) %>',{});
            return false;
    });
    //]]>
    </script>
<% end -%>

app/views/admin/indices/add_manager.js.erb
<% if @added -%>
    $("#index_users_<%= @index.id %>").html("<%= escape_javascript(render :partial => 'managers') %>");
    $("#index_<%= @index.id %>").effect('highlight',{ startcolor:'#ffff00'},8000);
<% else -%>
    $("#updater").html("<%= escape_javascript(render :partial => "share/error") %>");
    $("#updater").effect('slide', {});
<% end -%>

app/views/admin/indices/create.js.erb
<% if @created -%>
    $("#all_indices").prepend("<%= escape_javascript(render :partial => 'index') %>");
    $("#index_<%= @index.id %>").effect('highlight',{ startcolor:'#ffff00'},8000);
<% else -%>
    $("#updater").html("<%= escape_javascript(render :partial => "share/error") %>");
    $("#updater").effect('slide', {});
<% end -%>

app/views/admin/indices/index.html.erb
<% @title = t(:manage_indices, :scope => [:txt, :view, :admin, :indices]) -%>
<%= render :partial => 'admin/sub_menu_for_root' %>
<%= render_flash %>
<div class="option_wrap">

<div class="add_cate">
    <div id='add_category'>
	<%= form_tag(        admin_indices_path,
                            :remote => true, :id => "rform", :onsubmit => "return false;"
			    ) do %>
		<label for="index_title"><%= t(:title, :scope => [:txt, :view, :admin, :indices]) %>:</label>
		<%= text_field 'index', 'title', :size => 20  %>
	    <%= submit_tag t(:create, :scope => [:txt, :view, :admin, :groups]), :id => 's', :autocomplete => 'off', :disable_with => t(:saving, :scope => [:txt, :view, :admin, :groups]), :id => "subm" %> 
	<% end -%>	
    </div>	
<script type="text/javascript">
//<![CDATA[
        $('#subm').click(function(){
            $.post('<%= admin_indices_path %>',$('#rform').find('input').serialize());
            return false;
        });
//]]>
</script>
</div>
<div id="updater"></div>
<div id='groups'>
<table class="sofT" cellspacing="0" style="width:60%;">
    <tr>
	    <th class="helpHed"><%= t(:title, :scope => [:txt, :view, :admin, :indices]) %></th>
	    <th class="helpHed"><%= t(:bind_domain, :scope => [:txt, :view, :admin, :indices]) %></th>
	    <th class="helpHed"><%= t(:info, :scope => [:txt, :view, :admin, :indices]) %></th>
	    <th class="helpHed"><%= t(:theme, :scope => [:txt, :view, :admin, :indices]) %></th>
	    <th class="helpHed"><%= t(:managers, :scope => [:txt, :view, :admin, :indices]) %></th>
	    <th class="helpHed"></th>
    </tr>
    <tbody id="all_indices">
    <% for @index in @indices %>
	   <%= render :partial => "index" %> 
    <% end -%>	
    </tbody>
</table>
</div>

</div>
<%= in_place_edit_js :index, :title %>
<%= in_place_edit_js :index, :bind_domain %>
<%= in_place_edit_js :index, :info %>

app/views/admin/indices/remove_manager.js.erb
<% if @deleted -%>
    $("#index_users_<%= @index.id %>").html("<%= escape_javascript(render :partial => 'managers') %>");
    $("#index_<%= @index.id %>").effect('highlight',{ startcolor:'#ffff00'},8000);
<% else -%>
    $("#updater").html("<%= escape_javascript(render :partial => "share/error") %>");
    $("#updater").effect('slide', {});
<% end -%>

app/views/admin/indices/settings.html.erb
<%= render :partial => 'admin/sub_menu_for_index' %>
<%= render_flash %>
<div class="option_wrap">
<% @title =  t :settings, :scope => [:txt, :view, :admin, :index_settings] -%>
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><%= t(:avatar, :scope => [:txt, :view, :admin, :index_settings]) %></div>
<%= image_tag @index.avatar_url, :size => "60x60", :class => "favicon", :alt => "" %>
<%= form_for :index, :url => save_avatar_admin_index_path(@index), :html => {:multipart => true} do |f| -%>
    <%= file_field :file, :data, :accept => 'image/png' %>
    <br/>
    <%= submit_tag t(:upload, :scope => [:txt, :view, :admin, :settings]) %>
    <br/>
<% end -%>
</div>

<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><div id="notifier"></div><%= t :settings, :scope => [:txt, :view, :admin, :index_settings] %> </div>
<%= form_for(:index, :url => change_settings_admin_index_path(@index)) do |f| %>
    <label><%= t :main_title, :scope => [:txt, :view, :admin, :index_settings] %> 
    <%= f.text_field :main_title, :size => 50 %></label>
    <label><%= t :title_field, :scope => [:txt, :view, :admin, :index_settings] %></label> 
    <%= f.text_area :title_field, :style => "width:50%;height:100px;font-size:small;" %>
    <br/>
    <label><%= t :slogan, :scope => [:txt, :view, :admin, :index_settings] %> 
    <%= f.text_field :slogan, :size => 50 %></label>
    <label><%= t :post_number, :scope => [:txt, :view, :admin, :index_settings] %> 
    <%= f.text_field :new_post_number, :size => 6 %></label>
    <label><%= t :brief_cut, :scope => [:txt, :view, :admin, :index_settings] %> <%= f.text_field :post_brief_cut, :size => 6 %></label>
    <label><%= t :tail_field, :scope => [:txt, :view, :admin, :index_settings] %></label> 
    <%= f.text_area :tail_field, :style => "width:50%;height:100px;font-size:small;" %>
    <br/>
    <%= submit_tag t(:save, :scope => [:txt, :view, :admin, :settings]), :class =>'submit' %>
<% end %>
</div>
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><div id="notifier"></div><%= t(:theme_settings, :scope => [:txt, :view, :admin, :themes]) %> </div>
<%= form_for :index, :url => change_settings_admin_index_path(@index) do |f| %>
    <%= f.select :theme, @index_theme_list %>
    <label><%= t :plugin_css, :scope => [:txt, :view, :admin, :index_settings] %></label> 
    <%= f.text_area :plugin_css, :style => "width:80%;height:100px;font-size:small;" %>
    <br/>
    <%= submit_tag t(:save, :scope => [:txt, :view, :admin, :settings]), :class =>'submit' %>
<% end %>
</div>
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><div id="notifier"></div><%= t(:sidebar_layout_title, :scope => [:txt, :view, :admin, :sidebar]) %> - <%= t(:theme, :scope => [:txt, :view, :admin, :sidebar]) %> [ <%= @index.theme %> ] </div>
<%= form_for :index, :url => sidebar_position_admin_index_path(@index) do |f| %>
  <%= bars_layout(@index.theme) %>
  <br style="clear:both"/>
  <% @disable_bars ||= @all_bars.reject {|b| b.show? and @fields.include?(b.field.to_s)} -%>
  <div id="disable_bar_box">
	<div class="disable_bars_title"><%= t(:available_sidebars, :scope => [:txt, :view, :admin, :sidebar]) %></div>
	<ul id="disable" class="disable_hbars">
	  <% for bar in @disable_bars -%>
	     <%= show_bar(bar, :index) %>
	  <% end -%>
	</ul>
	<br style="clear:both"/>
  </div>
  <% @fields << 'disable' -%>
  <% @overlap[:disable] = :horizontal -%>

  <% for field in @fields -%>
    <%= hidden_field_tag 'fields[]', field %>
  <% end -%>
    <input class="submit" type="button" value="<%= t(:save, :scope => [:txt, :view, :admin, :sidebar]) %>" 
    onclick='sidebars_config(this.form, <%= @fields.inspect %>);this.form.submit();return false;'
	style=""/>
<% end %>
</div>

<% for field in @fields -%>
        <script type="text/javascript">
        //<![CDATA[
        jQuery('#<%= field %>').sortable({connectWith:<%=raw @fields.map{|x| "##{x}"}.inspect %>, dropOnEmpty:true, format:/^bar_(.*)$/})
        //]]>
        </script>
<% end -%>
</div>

app/views/admin/indices/show.html.erb
<% @title = t(:manage_indices, :scope => [:txt, :view, :admin, :indices]) -%>
<%= render :partial => "admin/sub_menu_for_index" %>
<%= render_flash %>
<div class="center">
<%= form_tag "", :onsubmit => "return false;" do -%>

<% if @posts.size >0 -%>
<table id="article_table" class="sofT" cellspacing="0" style="margin-top:5px;">
    <tr>
	    <th class="helpHed checkbox" style=""><%= check_box_tag "trigger", true, false, :onclick => "checkall(this.name, this.form)" %></th>	    
	    <th class="helpHed"><%= t(:username, :scope => [:txt, :view, :admin, :users]) %></th>
	    <th class="helpHed" style="text-align:left;"><%= t :title, :scope => [:txt, :view, :admin, :posts] %></th>
	    <th class="helpHed"><%= t :create_time,:scope => [:txt, :view, :admin, :posts]  %></th>
	    <th class="helpHed"><%= t :comments, :scope => [:txt, :view, :admin, :posts] %></th>
	    <th class="helpHed">Rank</th>
	    <th class="helpHed"></th>
    </tr>
    <% for post in @posts %>
        <% next unless post.user %> 
    <tr class="<%= cycle "odd", "" %>">
	    <td class="checkbox"><%= check_box_tag "ids[]", post.id, nil, :id => post.id %></td>
        <td class="user_name_col">
            <%= link_to post.user.name, root_url(:subdomain => post.user.name) %>
            <%= link_to image_tag("set.gif"), admin_users_path(:user_name => post.user.name) %>
        </td>
	    <td class="title_col"><%= link_to post_title(post), post_url(post, :subdomain => post.user.name, :format => :html), :class => "post_title_link"  %></td>
	    <td class="time_col"><%= post.created_at.to_s :db_short %></td>
	    <td class="comments_col"><%= link_to "(#{post.comments.count})", post_url(post, :anchor => "comments", :subdomain => post.user.name, :format => :html), :class => "post_comments", :target => '_blank' %></td>
	    <td class="category_col">
                <%= link_to "-", decrease_rank_admin_article_path(post), :remote => true, :method => :post, :class => "button_to_link",
                    :onclick => "show_spin('post#{post.id}_rank');" %>
                    <span id="<%= "post#{post.id}_rank" %>" class="post_rank"><%= post.rank %></span>
                <%= link_to "+", increase_rank_admin_article_path(post), :remote => true, :method => :post, :class => "button_to_link",
                    :onclick => "show_spin('post#{post.id}_rank');" %>
            </td>
	    <td class="action_col">
		<%= link_to t(:view, :scope => [:txt, :view, :admin, :posts]), post_url(post, :subdomain => post.user.name, :format => :html), :class => "read", :target => '_blank' %></td>
	    
    </tr>
    <% end -%>	
</table>
<% end -%>
<div id="pagilinks">
<%= will_paginate @posts, :previous_label => t("txt.prev_page"), :next_label => t("txt.next_page") %>
</div>
<% end -%>
</div>