config/routes.rb
Chito::Application.routes.draw do
  constraints(IndexMatch) do
    match '/' => 'index#index'
    match '/index.rss' => 'index#index', :as => :index_feed, :format => 'rss'
    match '/index_plugin.css' => 'index#plugin_css', :as => :index_plugin_css
  end
  root :to => 'posts#index'
  match '/plugin.css' => 'blog#plugin_css', :as => :plugin_css
  match '/simple_captcha(/:action)' => 'simple_captcha', :as => :simple_captcha
  match '/simple_captcha_ajax' => 'simple_captcha#simple_captcha_ajax'
  match '/:year/:month/:day/:permalink.:id.:format' => 'posts#show', :constraints => { :year => /(19|20)\d\d/, :month => /[0|1]?\d/, :day => /[0-3]?\d/ }, :as => :post_permalink
  match ':year/:month/:day' => 'posts#index', :as => :day, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/ }, :as => :posts_on
  match ':year/:month' => 'posts#index', :as => :archive, :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ }

  resources :posts do
    member do
        get :cancel_comment_notifier
    end 
  end

  resources :categories do
    resources :posts
  end
  resources :posts do
    resources :comments 
  end

  resources :pages
  resources :messages
  match '/comments.:format' => 'comments#index', :as => :comments
  match '/comments/:id/mark_as_spam.:format' => 'comments#mark_as_spam', :as => :mark_comment_as_spam
  match '/tag/*tag_name' => 'posts#index', :as => :tag_posts
  match '/category/*category_permalink' => 'posts#index', :as => :category_permalink_posts
  match '/admin/links/set_link_title' => 'admin/links#set_link_title'
  match '/admin/links/set_link_url' => 'admin/links#set_link_url'
  match '/admin/links/set_link_info' => 'admin/links#set_link_info'
  match '/admin/categories/set_category_name' => 'admin/categories#set_category_name'
  match '/admin/categories/set_category_info' => 'admin/categories#set_category_info'
  match '/admin/categories/set_category_permalink' => 'admin/categories#set_category_permalink'
  match '/admin/users/set_user_bind_domain' => 'admin/users#set_user_bind_domain'
  match '/admin/groups/set_group_space' => 'admin/groups#set_group_space'
  match '/admin/groups/set_group_file_size_limit' => 'admin/groups#set_group_file_size_limit'
  match '/admin/indices/set_index_title' => 'admin/indices#set_index_title'
  match '/admin/indices/set_index_bind_domain' => 'admin/indices#set_index_bind_domain'
  match '/admin/indices/set_index_info' => 'admin/indices#set_index_info'

  namespace :admin do
    resources :posts do
        collection do
            post :destroy_selected
            post :recategory_selected
        end
        member do
            post :autosave
        end
    end

    resources :drafts do
        collection do
            post :destroy_selected
        end
        member do
            post :autosave
        end
    end

    resources :trash do
        collection do
            post :destroy_all
        end
        member do
            post :restore
        end
    end

    resources :pages do
        member do
            post :enable_fontpage
            post :cancel_fontpage
        end
        member do
            post :autosave
        end
    end
      
    resources :users do 
        member do
            post :set_group
        end
    end
    
    resources :groups do
        member do
            post :set_group_space
            post :set_group_name
            post :set_group_file_size_limit
            post :set_api_status
            post :set_no_index_status
        end
    end

    resources :indices do
        member do
            post :add_manager
            post :remove_manager
            get :settings
            post :change_settings
            post :sidebar_position
            post :save_avatar
        end
    end

    resources :comments do
        collection do
            delete :destroy_selected
        end
    end

    resources :messages do
        collection do
            delete :destroy_selected
        end
    end

    resources :trackbacks do
        collection do
            delete :destroy_selected
        end
    end

    resources :talks

    resources :spams do
        collection do
            delete :destroy_selected
        end
        member do
            post :pass
        end
    end

    resources :categories do
        resources :posts
        resources :drafts
        collection do
            post :set_position
        end
    end
      
    resources :links do
        collection do
            post :set_position
        end
    end

    resources :files do
        collection do
            get :list
            get :create_file_iframe
            post :create_file_iframe
            delete :delete_file
            delete :delete_dir
            post :create_file
            post :create_dir
        end
    end
      
    resources :feedbacks do
        collection do
            delete :destroy_selected
        end
    end
    
    resources :articles do
        collection do
            delete :destroy_selected
        end
        member do
            post :increase_rank
            post :decrease_rank
        end
    end

  end

  #match '/latex_formula/make_png' => 'latex_formula#make_png'

  match '/xmlrpc' => 'xmlrpc/meta_weblog#index', :format => 'xml'
  match '/xml_rpc' => 'xmlrpc/meta_weblog#index', :format => 'xml'

  match '/add' => 'blog#add'
  match '/login' => 'blog#login', :as => :login
  match '/forgot_password' => 'blog#forgot_password', :as => :forgot_password
  match '/reset_password/:key' => 'blog#reset_password', :as => :reset_password
  match '/guestbook' => 'blog#guestbook', :as => :guestbook
  match '/articles/:id/:seo_title.:format' => 'posts#show'
  match '/rss' => 'posts#index', :format => 'rss'
  match '/feed' => 'posts#index', :as => :feed, :format => 'rss'
  match '/show/:id.:format' => 'posts#show'
  match '/site.:format' => 'blog#index', :as => :site
  match '/setup' => 'site#setup'
  match '/pages/:id/:seo_title.:format' => 'pages#show'
  match '/themes/user/:theme/*anything' => 'theme#user_theme_file'
  match '/themes/index/:theme/*anything' => 'theme#index_theme_file'
  match '/plugins/:plugin/*anything' => 'plugin#file'
  match '/admin' => 'admin/dashboard#index', :as => :admin
  match '/admin/logout' => 'admin/dashboard#logout'
  match '/admin/dashboardbar_position' => 'admin/dashboard#dashboardbar_position'
  match '/admin/plugins/(:plugin_id)' => 'admin/plugins#index'
  match '/admin/plugin_config/:plugin_id' => 'admin/plugins#plugin'
  match '/admin/remote_form/:plugin/:view' => 'admin/plugins#remote_form'
  match '/admin/remote_update' => 'admin/plugins#remote_update'
  match '/admin/themes/:action/(:id)' => 'admin/themes#index'
  match '/admin/themesettings/:action/(:id)' => 'admin/themesettings#index'
  match '/admin/sidebar/:action/(:id)' => 'admin/sidebar#index'
  match '/admin/navbar/:action/(:id)' => 'admin/navbar#index'
  match '/admin/postbar/:action/(:id)' => 'admin/postbar#index'
  match '/admin/settings/comment/setting_area' => 'admin/settings#comment_setting_area', :as => :admin_comment_setting_area
  match '/admin/settings/comment/set_comment_system' => 'admin/settings#set_comment_system_settings', :as => :admin_set_comment_system
  match '/admin/settings/:action/(:id)' => 'admin/settings#index'
  match '/admin/rss/:action/(:id)' => 'admin/rss#index'
  match '/admin/site/:action/(:id)' => 'admin/site#index'
  match '/admin/blog/:action/(:id)' => 'admin/blog#index'
  match '/admin/systeminfo/:action/(:id)' => 'admin/systeminfo#index'
  match '/admin/:action/:id' => 'admin/dashboard#index'
  match '/*permalink' => 'pages#show', :as => :page_permalink
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController

  def info
    return unless request.post?
    if @user.update_attributes(params[:user])
        notice_stickie t(:profile_updated, :scope => [:txt, :controller, :admin, :settings])
    else
        error_stickie @user.errors.full_messages * "; "
    end
    redirect_to :action => 'info'
  end

  def blog
    return unless request.post?
    update_user_and_redirect_to :blog
  end

  def admin_style
    return unless request.post?
    @user.admin_style = params[:user][:admin_style]
    @user.save
    redirect_to :action => 'system'
  end

  def avatar_info
    return unless request.post?
    update_user_and_redirect_to :info
  end

  def save_avatar
    file = params[:file] && params[:file][:data]
    if file.respond_to?('content_type')  && file.content_type =~ /^image/ && file.size < 204800
        @user.avatar = file
        notice_stickie t(:avatar_uploaded, :scope => [:txt, :controller, :admin, :settings])
    else
        error_stickie t(:avatar_format_error, :scope => [:txt, :controller, :admin, :settings])
    end
    redirect_to :action => "info"
  end

  def save_favicon
    file = params[:file] && params[:file][:data]
    if file.respond_to?('content_type')  && file.content_type =~ /^image/ && file.size < 20480
        @user.favicon = file
        notice_stickie t(:favicon_uploaded, :scope => [:txt, :controller, :admin, :settings])
    else
        error_stickie t(:favicon_format_error, :scope => [:txt, :controller, :admin, :settings])
    end
    redirect_to :action => "info"
  end

  def change_password
    old, new, _new = params[:old], params[:new], params[:_new]
    if new == _new 
        if @user.hashed_password == User.hash_password(old, @user.salt)
            @user.password = new
            notice_stickie t(:password_updated, :scope => [:txt, :controller, :admin, :settings]) if @user.save
        else
            error_stickie t(:password_invalid, :scope => [:txt, :controller, :admin, :settings])
        end
    else
        error_stickie t(:password_dismatch, :scope => [:txt, :controller, :admin, :settings])
    end
    redirect_to :action => 'system'
  end

  def system
  end

  def comment

  end

    def comment_setting_area
        system = params[:system] || @user.comment_system
        if system == 'disqus'
            @area = 'disqus_comment_settings'
        else
            get_chito_comment_system_settings
            @area = 'chito_comment_settings'
        end
    end

    def set_comment_system_settings
        get_comment_filters
        for field in ["enable_filters", "disable_filters"]
            next unless params[field.to_sym]
            params[field.to_sym].each_with_index do |id,idx| 
                bar = @filters.detect{|s| s.id == id.to_sym}
                bar.position = idx
                bar.enable = (field.to_sym == :enable_filters)
            end
        end
        @user.update_attributes(params[:user])
        notice_stickie t(:filter_settings_updated, :scope => [:txt, :controller, :admin, :comments])
        redirect_to :action => "comment"
    end

    private

    def get_chito_comment_system_settings
        get_comment_filters
        @enable_filters, @disable_filters = @filters.separate {|x| x.enable}
    end
end

app/views/admin/settings/_chito_comment_settings.html.erb
    <label><%= check_box :user, :enable_thread_comment, :class => 'checkbox' %> <%= t(:enable_thread_comment, :scope => [:txt, :view, :admin, :settings]) %></label>
    <label><%= check_box :user, :check_comment_notifier_by_default, :class => 'checkbox' %> <%= t(:check_comment_notifier_by_default, :scope => [:txt, :view, :admin, :settings]) %></label>

   <label><%= t(:filter_chain, :scope => [:txt, :view, :admin, :comments]) %></label>
   <div id="filters"> 
    <div class="comment_box"><%= t(:a_comment, :scope => [:txt, :view, :admin, :comments]) %></div><div class="point_box"></div>
    <ul id="enable_filters">
	<% for f in @enable_filters -%>
	    <%= show_filter(f) %>
	<% end -%>
    </ul>
    <div class="point_box"></div>
    <div class="comment_box"><%= t(:save, :scope => [:txt, :view, :admin, :comments]) %></div>

   </div>
   <div id="disable_filters_box">
	<div class="disable_bars_title"><%= t(:available_comment_filters, :scope => [:txt, :view, :admin, :comments]) %></div>   
    <ul id="disable_filters">
	<% for f in @disable_filters -%>
	    <%= show_filter(f) %>
	<% end -%>    
    </ul>
	<br style="clear:both"/>    
   </div>

<script type="text/javascript">
//<![CDATA[
jQuery('#disable_filters').sortable({connectWith:['#enable_filters','#disable_filters'], dropOnEmpty:true, format:/^bar_(.*)$/})
//]]>
</script>
    <script type="text/javascript">
//<![CDATA[
jQuery('#enable_filters').sortable({connectWith:['#enable_filters','#disable_filters'], dropOnEmpty:true, format:/^bar_(.*)$/})
//]]>
</script>

app/views/admin/settings/_disqus_comment_settings.html.erb
<label><%= "Disqus shortname" %>: <%= text_field :user, :disqus_shortname, :size => '15'%></label>

app/views/admin/settings/blog.html.erb
<% @title = t(:blog_options, :scope => [:txt, :view, :admin, :settings]) -%>
<%= render :partial => 'admin/sub_menu_for_setting' %>
<%= render_flash %>
<div class="option_wrap">
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><%= t(:post, :scope => [:txt, :view, :admin, :settings]) %></div>
<%= form_for :user do |f| %>
    <label><%= f.check_box :auto_redirect_to_permalink, :class => 'checkbox' %> <%= t(:auto_redirect_to_permalink, :scope => [:txt, :view, :admin, :settings]) %></label>
    <%= submit_tag t(:save, :scope => [:txt, :view, :admin, :settings]), :class =>'submit' %>
<% end %>
</div>

<!-- TODO: Disable for no spam protection
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><%= t(:trackback, :scope => [:txt, :view, :admin, :settings]) %></div>
<%= form_for :user do |f| %>
    <label><%= f.check_box :show_trackbacks, :class => 'checkbox' %> <%= t(:show_trackback, :scope => [:txt, :view, :admin, :settings]) %></label>
    <label><%= f.check_box :enable_trackbacks, :class => 'checkbox' %> <%= t(:enable_trackback, :scope => [:txt, :view, :admin, :settings]) %></label>
    <%= submit_tag t(:save, :scope => [:txt, :view, :admin, :settings]), :class =>'submit' %>
<% end %>
</div>
-->

<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><%= t(:paginate, :scope => [:txt, :view, :admin, :settings]) %></div>
<%= form_for :user do |f| %>
    <label><%= t(:posts_pre_page, :scope => [:txt, :view, :admin, :settings]) %>: <%= f.text_field :blog_per_page, :size => '5' %> <%= t(:default, :scope => [:txt, :view, :admin, :settings], :num => 10) %></label>
    <%= expire_cache_field :type => "posts_index/*" %>
    <%= submit_tag t(:save, :scope => [:txt, :view, :admin, :settings]), :class =>'submit' %>
<% end %>
</div>

<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><%= t(:RSS, :scope => [:txt, :view, :admin, :settings]) %></div>
    <%= form_for :user do |f| %>
    <label><%= f.radio_button :rss_type, 'full', :checked => true,  :class => 'ck' %> <%= t(:full, :scope => [:txt, :view, :admin, :settings]) %></label>
    <label><%= f.radio_button :rss_type, 'brief',  :class => 'ck' %> <%= t(:brief, :scope => [:txt, :view, :admin, :settings]) %></label>
    <%= submit_tag t(:save, :scope => [:txt, :view, :admin, :settings]), :class =>'submit' %>
<% end %>
</div>

</div>

app/views/admin/settings/comment.html.erb
<% @title = t(:comment_settings, :scope => [:txt, :view, :admin, :comments]) -%>
<%= render :partial => "admin/sub_menu_for_setting" %>
<%= render_flash %>
<div class="option_wrap">
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><div id="notifier"></div><%= t(:comment_system_settings, :scope => [:txt, :view, :admin, :comments]) %></div>

<%= form_for :user, :url => admin_set_comment_system_path do |f| %>

    <label style="font-weight:bold;font-size:120%;"><%= f.radio_button :comment_system, 'chito', :class => 'ck' %> <%= "Chito default" %></label>
    <label style="font-weight:bold;font-size:120%;"><%= f.radio_button :comment_system, 'disqus',  :class => 'ck' %> <%= "Disqus" %></label>

    <div id="comment_system_settings" style="padding:25px 0px 20px 12px;border-top:1px dashed #666;margin-top:30px;">
    </div>

<input class="submit" type="button" value="<%= t(:save, :scope => [:txt, :view, :admin, :comments]) %>" onclick='filter_config(this.form);this.form.submit();return false;'/>   

<% end -%>
</div>
</div>
<script type="text/javascript">
//<![CDATA[
function show_settings_area()
{
    show_spin('comment_system_settings');
    if($(this).val())
        $.get("<%= admin_comment_setting_area_path(:format => :js) %>" + "?system=" + $(this).val());
    else
        $.get("<%= admin_comment_setting_area_path(:format => :js) %>" );
}
$('.ck').change(show_settings_area);

$(document).ready(show_settings_area);
//]]>
</script>

app/views/admin/settings/comment_setting_area.js.erb
$("#comment_system_settings").html("<%= escape_javascript(render :partial => @area) %>");

app/views/admin/settings/info.html.erb
<% @title = t(:profile, :scope => [:txt, :view, :admin, :settings]) -%>
<%= render :partial => 'admin/sub_menu_for_setting' %>
<%= render_flash %>
<div class="option_wrap">
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><%= t(:avatar, :scope => [:txt, :view, :admin, :settings]) %></div>
<div id="head_pic">
    <div id="head" style="width:125px;">
	<%= image_tag @user.avatar_url, :size => "120x120" %>
	<div id="info" style='text-align:center;'> <%= @user.info %></div>
    </div>	
</div>
<div id="head_option">
<label><%= t(:upload_new, :scope => [:txt, :view, :admin, :settings]) %>:</label>
<%= form_for :user, :url => {:action => 'save_avatar'}, :html => {:multipart => true} do |f| -%>
    <%= file_field :file, :data, :accept => 'image/png' %>
    <%= submit_tag t(:upload, :scope => [:txt, :view, :admin, :settings]) %>
    <br/>
<% end -%>
<%= t(:pic_format, :scope => [:txt, :view, :admin, :settings]) %>
<label><%= t(:pic_info, :scope => [:txt, :view, :admin, :settings]) %>:</label>
<%= form_for :user, :url => {:action => 'avatar_info'} do |f| %>
    <%= f.text_field 'info', :size => '50' %>
    <%= submit_tag t(:save, :scope => [:txt, :view, :admin, :settings]), :class =>'submit' %>
<% end %>
</div>
</div>
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><%= t(:favicon, :scope => [:txt, :view, :admin, :settings]) %></div>
<%= image_tag favicon_url, :size => "16x16", :class => "favicon", :alt => "" %>
<%= form_for :user, :url => {:action => 'save_favicon'}, :html => {:multipart => true} do |f| -%>
    <%= file_field :file, :data, :accept => 'image/ico' %>
    <%= submit_tag t(:upload, :scope => [:txt, :view, :admin, :settings]) %>
    <%= link_to t(:refresh_favicon, :scope => [:txt, :view, :admin, :settings]), favicon_url, :target => "_blank" %>
    <br/>
    <span style="padding-left:36px;"><%= t(:favicon_format, :scope => [:txt, :view, :admin, :settings]) %>
<% end -%>
</div>
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><%= t(:change_profile, :scope => [:txt, :view, :admin, :settings]) %></div>
<%= form_for :user, :url =>{:action => 'info'} do |f| %>
    <label><%= t(:title, :scope => [:txt, :view, :admin, :settings]) %>:</label>
    <%= f.text_field 'title', :size => '40'%>
    <br/>
    <label><%= t(:slogan, :scope => [:txt, :view, :admin, :settings]) %>:</label>
    <%= f.text_field 'slogan', :size => '100'%><br/> 
    <%= f.check_box :show_slogan_in_title, :class => "ck" %> <%= t("txt.view.admin.settings.show_slogan_in_title") %>
    <br/>
    <label><%= t(:nick, :scope => [:txt, :view, :admin, :settings]) %>:</label>
    <%= f.text_field 'nick', :size => '10'%>
    <br/>
    <label >E-mail:</label>
    <%= f.text_field 'email', :size => '25' %>
    <label >Twitter:</label>
    <%= f.text_field 'twitter', :size => '15' %>
    <label >Language:</label>
    <%= f.select :language, Chito::LANGUAGES %>
    <label ><%= t(:time_zone, :scope => [:txt, :view, :admin, :settings]) %>:</label>
        <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.all %>
    <br/>
    <br/>
    <%= submit_tag t(:save, :scope => [:txt, :view, :admin, :settings]), :class =>'submit' %>
<% end %>
</div>


</div>

app/views/admin/settings/rss.html.erb
<% @title = t(:message_0, :scope => [:txt, :view, :admin, :settings]) -%>
<%= render :partial => 'admin/sub_menu_for_setting' %>
<%= render_flash %>
<div class="option_wrap">
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><%= t(:message_1, :scope => [:txt, :view, :admin, :settings]) %></div>
    <%= form_for :user, :url => {:action => :rss} do |f| %>
    <label><%= f.radio_button :rss_type, 'full', :checked => true,  :class => 'ck' %> <%= t(:message_2, :scope => [:txt, :view, :admin, :settings]) %></label>
    <label><%= f.radio_button :rss_type, 'brief',  :class => 'ck' %> <%= t(:message_3, :scope => [:txt, :view, :admin, :settings]) %></label>
    <label><%= t(:message_4, :scope => [:txt, :view, :admin, :settings]) %>: <%= f.text_field :rss_number, :size => '5' %> <%= t(:message_5, :scope => [:txt, :view, :admin, :settings]) % {:num => 12} %></label>
    <%= submit_tag t(:message_6, :scope => [:txt, :view, :admin, :settings]), :class =>'submit' %>
<% end %>
</div>
</div>

app/views/admin/settings/system.html.erb
<% @title = t(:message_0, :scope => [:txt, :view, :admin, :settings]) -%>
<%= render :partial => 'admin/sub_menu_for_setting' %>
<%= render_flash %>
<div class="option_wrap">
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><%= t(:message_1, :scope => [:txt, :view, :admin, :settings]) %></div>
<%= form_tag :action => :change_password do |f|%>
	<label><%= t(:message_2, :scope => [:txt, :view, :admin, :settings]) %></label>
	<%= password_field_tag 'old', nil, :size => '15' %><br/>
	<label><%= t(:message_3, :scope => [:txt, :view, :admin, :settings]) %></label>
	<%= password_field_tag 'new', nil, :size => '15' %><br/>
	<label><%= t(:message_4, :scope => [:txt, :view, :admin, :settings]) %></label>
	<%= password_field_tag '_new', nil, :size => '15' %><br/>
	<%= submit_tag t(:message_5, :scope => [:txt, :view, :admin, :settings]), :class => 'submit' %>
<% end %>
</div>
<div class="edit_field">
<div class="right_c"></div>
<div class="edit_header"><%= t(:message_6, :scope => [:txt, :view, :admin, :settings]) %></div>
<%= form_for :user, :url => {:action => :admin_style} do |f|%>
	<label><%= f.radio_button :admin_style, 'green', :class => 'ck' %> <%= t(:message_7, :scope => [:txt, :view, :admin, :settings]) %></label>
	<label><%= f.radio_button :admin_style, 'blue' , :class => 'ck' %> <%= t(:message_8, :scope => [:txt, :view, :admin, :settings]) %></label>
	<label><%= f.radio_button :admin_style, 'grey' , :class => 'ck' %> <%= t(:grey, :scope => [:txt, :view, :admin, :settings]) %></label>
	<%= submit_tag t(:message_9, :scope => [:txt, :view, :admin, :settings]), :class => 'submit' %>
<% end %>
</div>
</div>